name: gestionConge
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.17
  liquid_swipe: ^3.0.0
  get:
  smooth_page_indicator: ^1.0.1
  otp_text_field: ^1.1.3
  shared_preferences: ^2.0.15
  http: ^0.13.4
  fitted_text_field_container: ^2.0.0
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  syncfusion_flutter_calendar: ^19.1.59
  line_icons: ^2.0.1
  get_storage:
  intl:
  date_picker_timeline:
  flutter_local_notifications:
  flutter_native_timezone:
  flutter_staggered_animations: ^1.1.1
  timezone: ^0.7.0
  sqflite: ^2.0.0+3
  flutter_spinkit: ^5.1.0
  rxdart: ^0.27.2









dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/.jpeg
  image_dark: assets/images/men.png

  android_12:
    image: assets/images/men.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/men.png
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png
    - assets/images/register.png
    - assets/images/login.png
    - assets/images/top_background.png
    - assets/images/top_background1.png
    - assets/images/top_background2.png
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/men.png
    - assets/images/ppl1.jpg
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.png
    - assets/images/5.png
    - assets/images/ent.jpg
    - assets/images/homescreen.png